# Generated by Django 4.2.23 on 2025-07-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Address_line_2',
            new_name='address_line_2',
        ),
    ]
